---
- hosts: all
  become: yes
  tasks:
  - name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup 
    ansible.builtin.copy:
      src: eth1
      dest: /etc/network/interfaces.d/eth1
      validate: /usr/sbin/ifup --no-act -i %s eth1
    notify: reboot

  handlers:
  - name: reboot
    reboot: