Vagrant.configure("2") do|config|
    config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    end  
    config.vm.box = "las/bullseye64"
    config.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    end
