Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bullseye64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end

   config.vm.define "router" do |machine|
      machine.vm.hostname = "router"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.network "private_network", ip: "192.168.57.10"
   end

   config.vm.define "client" do |machine|
      machine.vm.hostname = "client"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.network "private_network", ip: "192.168.57.20"
   end
   
   config.vm.define "server1" do |machine|
      machine.vm.hostname = "server1"
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.network "private_network", ip: "192.168.57.30"
   end

   config.vm.define "server2" do |machine|
      machine.vm.hostname = "server2"
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.network "private_network", ip: "192.168.57.40"
   end

   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
   end
end
