routers:
  hosts:
    router1:
      static_interfaces:
      - name: "eth1"
        ip: "172.16.1.1"
        netmask: "255.255.255.0"
      - name: "eth2"
        ip: "192.168.56.101"
        netmask: "255.255.255.0"
      routes:
      - name: "eth2"
        dest: "172.16.2.0/24"
        gateway: "192.168.56.102"
      dnsmasq:
        interfaces:
        - "eth1"
        ranges:
        - begin: "172.16.1.50"
          end: "172.16.1.150"
          lease: "12h"
        # ntp_servers:
        # - "10.10.10.254"
        # - "20.20.0.1"
        dns_servers:
        - "172.16.1.1"
        routes:
        - name: "eth1"
          network: "172.16.2.0/24"
          gateway: "172.16.1.1"
        # fixed_hosts:
        # - mac: "08:00:27:09:A5:01"
        #   ip: "10.200.2.1"
        #   hostname: "servermain"
        #   lease: "12h"
    router2:
      static_interfaces:
      - name: "eth1"
        ip: "172.16.2.1"
        netmask: "255.255.255.0"
      - name: "eth2"
        ip: "192.168.56.102"
        netmask: "255.255.255.0"
      routes:
      - name: "eth2"
        dest: "172.16.1.0/24"
        gateway: "192.168.56.101"
      dnsmasq:
        interfaces:
        - "eth1"
        ranges:
        - begin: "172.16.2.50"
          end: "172.16.2.250"
          lease: "12h"
            #ntp_servers:
            #- "10.30.0.1"
        dns_servers:
        - "172.16.2.1"
        routes:
        - name: "eth1"
          network: "172.16.1.1/24"
          gateway: "172.16.2.1"
            # fixed_hosts:
            #- mac: "08:00:27:09:A5:01"
            #ip: "10.30.2.1"
            #hostname: "servermain"
            #lease: "12h"
