Vagrant.configure("2") do|config|
    #
    # Run Ansible from the Vagrant Host
    #
       config.vm.box = "las/bullseye64"
       config.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook.yml"
       end
    end