routers:
  hosts:
    router:
      static_interfaces:
      - name: "eth1"
        ip: "192.168.10.1"
        netmask: "255.255.255.0"
      - name: "eth2"
        ip: "192.168.20.1"
        netmask: "255.255.255.0"
      dnsmasq:
        interfaces:
        - "eth1"
        - "eth2"
        ranges:
        - begin: "192.168.10.10"
          end: "192.168.10.20"
          lease: "12h"
        - begin: "192.168.20.10"
          end: "192.168.20.20"
          lease: "12h"
        dns_servers:
        - "192.168.10.1"
        - "192.168.20.1"
        routes:
        - name: "eth1"
          network: "192.168.20.0/24"
          gateway: "192.168.10.1"
        - name: "eth2"
          network: "192.168.10.0/24"
          gateway: "192.168.20.1"
          fixed_hosts:
          - mac: "08:00:27:09:A5:01"
          ip: "10.200.2.1"
          hostname: "servermain"
          lease: "12h"
