Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bullseye64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end

   config.vm.define "controller" do |machine|
      machine.vm.hostname = "controller"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
   end

   config.vm.define "agent1" do |machine|
      machine.vm.hostname = "agent1"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
   end
   
   config.vm.define "agent2" do |machine|
      machine.vm.hostname = "agent2"
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
   end

   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
   end
end
