routers:
  hosts:
    router:
      static_interfaces:
      - name: "eth1"
        ip: "R1-H1"
        netmask: "255.255.0.0"
      - name: "eth2"
        ip: "R1-H2"
        netmask: "255.255.0.0"
      dnsmasq:
        interfaces:
        - "eth1"
        - "eth2"
        ranges:
        - begin: "BEGINR1"
          end: "ENDR1"
          lease: "12h"
        - begin: "BEGINR2"
          end: "ENDR2"
          lease: "12h"
        dns_servers:
        - "R1-H1"
        - "R1-H2"
        routes:
        - name: "eth1"
          network: "NETR2/16"
          gateway: "R1-H1"
        - name: "eth2"
          network: "NETR1/16"
          gateway: "R1-H2"
          fixed_hosts:
          - mac: "08:00:27:09:A5:01"
          ip: "10.200.2.1"
          hostname: "servermain"
          lease: "12h"
