---
- hosts: all
  become: yes
  tasks:
    - name: "Add the user'johnd'"
      ansible.builtin.user:
        name: johnd
        password: $6$Id2EC2WZxCiz2oVz$Opln/4mWOT9Yi6bajwuZ3/nAO3JF2dxDNxwbx9C9pU7JIrIyeJSFMMDRvTTOIEQP4.n6.4uz8GoOlExC/VUcu.
        expires: -1
        create_home: True

    - name: Install and enable atd
      ansible.builtin.package:
        name: at
        state: present
    
    - name: Guarantee atd is started
      ansible.builtin.systemd:
        state: started
        name: atd.service