Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bullseye64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end

   config.vm.define "router" do |machine|
      machine.vm.hostname = "router"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
   end

   config.vm.define "client" do |machine|
      machine.vm.hostname = "client"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
   end
      
   config.vm.define "server" do |machine|
      machine.vm.hostname = "server"
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false, mac:"08002709A501"
   end

   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
   end
end
