Vagrant.configure("2") do |config| 
    config.vm.box = "las/bullseye64"
 
    config.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    config.vm.provider "virtualbox" do |vb|
       vb.linked_clone = true
    end     
 
    config.vm.define "client" do |machine|
       machine.vm.hostname = "client"
    end
 
    config.vm.define "router" do |machine|
       machine.vm.hostname = "router"
    end
    
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
     end
   end