routers:
  hosts:
    router1:
      static_interfaces:
      - name: "eth1"
        ip: "10.100.100.1"
        netmask: "255.255.255.0"
      - name: "eth2"
        ip: "172.10.10.254"
        netmask: "255.255.255.0"
      routes:
      - name: "eth2"
        dest: "10.200.200.0/24"
        gateway: "172.10.10.1"
      dnsmasq:
        interfaces:
        - "eth1"
        ranges:
        - begin: "10.100.100.10"
          end: "10.100.100.20"
          lease: "12h"
        dns_servers:
        - "10.100.100.1"
        routes:
        - name: "eth1"
          network: "10.200.200.0/24"
          gateway: "10.100.100.1"
        # fixed_hosts:
        # - mac: "08:00:27:09:A5:01"
        #   ip: "10.200.2.1"
        #   hostname: "servermain"
        #   lease: "12h"
    router2:
      static_interfaces:
      - name: "eth1"
        ip: "10.200.200.1"
        netmask: "255.255.255.0"
      - name: "eth2"
        ip: "172.10.10.1"
        netmask: "255.255.255.0"
      routes:
      - name: "eth2"
        dest: "10.100.100.0/24"
        gateway: "172.10.10.254"
      dnsmasq:
        interfaces:
        - "eth1"
        ranges:
        - begin: "10.200.200.10"
          end: "10.200.200.20"
          lease: "12h"
        dns_servers:
        - "10.200.200.1"
        routes:
        - name: "eth1"
          network: "10.100.100.0/24"
          gateway: "10.200.200.1"
            # fixed_hosts:
            #- mac: "08:00:27:09:A5:01"
            #ip: "10.30.2.1"
            #hostname: "servermain"
            #lease: "12h"
