---
- name: Verify apache installation
  hosts: all
  become: yes
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: Write the apache config file
    ansible.builtin.template:
      src: test
      dest: /home/vagrant/test
    notify:
    - Restart apache
    
  - name: Ensure apache is running
    ansible.builtin.service:
      name: apache2
      state: started

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
       
