- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes
- name: Copy dnsmasq configuration file
  copy:
    src: "{{ inventory_hostname }}/dnsmasq.conf"
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq
- name: "interfaces"
  lineinfile:
    path: "/etc/dnsmasq.conf"
    line: "interface={{ item }}"
  loop: "{{ dnsmasq.interfaces }}"
  when: dnsmasq.interfaces is defined
- name: "ranges"
  lineinfile:
    path: "/etc/dnsmasq.conf"
    line: "dhcp-range={{ item.begin }},{{ item.end }},{{ item.lease }}"
  loop: "{{ dnsmasq.ranges }}"
  when: dnsmasq.ranges is defined
- name: "ntp_servers"
  lineinfile:
    path: "/etc/dnsmasq.conf"
    line: "dhcp-option=option:ntp-server,{{ item }}"
  loop: "{{ dnsmasq.ntp_servers }}"
  when: dnsmasq.ntp_servers is defined
- name: "interfaces"
  lineinfile:
    path: "/etc/dnsmasq.conf"
    line: "dhcp-option=6,{{ item }}"
  loop: "{{ dnsmasq.dns_servers }}"
  when: dnsmasq.dns_servers is defined
- name: "routes"
  lineinfile:
    path: "/etc/dnsmasq.conf"
    regexp: '^dhcp-option=121'
    line: "dhcp-option=121,{{ item.network1 }},{{ item.gateway1 }}"
  loop: '{{ dnsmasq.routes }}'
  when: dnsmasq.routes is defined
- name: "hosts"
  lineinfile:
    path: "/etc/dnsmasq.conf"
    line: "dhcp-host={{ item.mac }},{{ item.ip }},{{ item.hostname }},{{ item.lease }}"
  loop: "{{ dnsmasq.fixed_hosts }}"
  when: dnsmasq.fixed_hosts is defined