---
- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: eth1_cfg
    dest: /etc/network/interfaces.d/eth1_cfg
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Install snmpd
  ansible.builtin.apt:
    name: snmpd
    update_cache: true
  
- name: Copy a snmpd.conf
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  notify: Restart SNMP