---
- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: eth1_cfg
    dest: /etc/network/interfaces.d/eth1_cfg
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: eth2_cfg
    dest: /etc/network/interfaces.d/eth2_cfg
    validate: /usr/sbin/ifup --no-act -i %s eth2
  notify: Restart Networking

- name: Enable Forwarding between client and server
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Install Dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    update_cache: true

- name: Copy Dnsmasq configuration
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: '/etc/dnsmasq.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart Dnsmasq

- name: Enable Dnsmasq at boot
  ansible.builtin.systemd:
    name: dnsmasq.service
    state: started
    enabled: yes

- name: Add static entry for client to /etc/hosts
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    line: '10.1.1.1 client'

- name: Add static entry for server to /etc/hosts
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    line: '10.2.2.2 server'
